apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.rewardCalculator.name }}-acc'
  labels:
    app.kubernetes.io/instance: "{{ .Values.rewardCalculator.name }}-app"
    partner.reward/app: {{ .Values.rewardCalculator.name }}

