---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.calcSchemeService.name }}-acc"
  labels:
    app.kubernetes.io/instance: "{{ .Values.calcSchemeService.name }}-app"
    partner.reward/app: {{ .Values.calcSchemeService.name }}
