auth:
  postgresPassword: postgres
  database: calc_scheme

nameOverride: "calc-scheme-service"
fullnameOverride: "calc-scheme-service"
calcSchemeService:
    name: calc-scheme-service
    image: babybenz/partner-reward
    imageTag: calc-scheme-service-0.0.2-SNAPSHOT
    imagePullPolicy: Always
    port: 8082

replicaCount: 1

serviceAccount:
  create: true
  name: "calc-scheme-service"

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 64Mi

postgresql:
  fullnameOverride: "calc-scheme-service-postgresql"
