---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.eventProcessor.name }}-acc"
  labels:
    app.kubernetes.io/instance: "{{ .Values.eventProcessor.name }}-app"
    partner.reward/app: {{ .Values.eventProcessor.name }}
