# Default values for reward.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  postgresql:
    auth:
      postgresPassword: postgres
      database: partner_reward

kafka:
  externalAccess:
    enabled: true
    service:
      type: ClusterIP
      domain: "10.102.44.253"
