---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.profilePointService.name }}-service"
  labels:
    app.kubernetes.io/instance: "{{ .Values.profilePointService.name }}-app"
    partner.reward/app: {{ .Values.profilePointService.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.profilePointService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: "{{ .Values.profilePointService.name }}-app"
    partner.reward/app: {{ .Values.profilePointService.name }}