spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/partner_revenue
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  messages:
    basename: classpath:i18n/messages
    encoding: UTF-8
logging:
  level:
    ROOT: DEBUG
