nameOverride: "report"
fullnameOverride: "report"
report:
    name: report
    image: babybenz/partner-reward
    imageTag: report-0.0.2-SNAPSHOT
    imagePullPolicy: Always
    port: 8084

replicaCount: 1

serviceAccount:
  create: true
  name: "report"

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 64Mi

postgresql:
  fullnameOverride: "report-postgresql"
